### ISSUE TITLE
"tell me more" should not be handled by this skill

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/skill-ovos-volume#23]
When try to search something on Wikipedia, I got surprised when this skill handled the query!

```
tell me more about chocolate
 >> Volume set to 60 percent
```

**Comment by goldyfruit** [comment]
Not an issue anymore.

**Comment by JarbasAl** [comment]
the move to padacioso over padatious in default config probably fixed a few issues like this one

**Comment by JarbasAl** [comment]
since padacioso is very slow, we reverted to padatious, so this is an issue again

several tings to be done:
- allow "exclude" keywords in intents, planned for after 0.1.0
- remove padatious medium/low matches from default pipeline, we cant do it for backwards compat yet, but users can change their mycroft.conf
- get rid of padatious completely, also on TODO list for after 0.1.0, it's just not very accurate

keeping this issue open for discoverability
